### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by yukachan3** [shoushouminami/LaiLaiMail#1]
您好！！！
您的圣来mail自动生成图的项目十分有趣。
在下想问一下，您的自动生成能否通过更改header等固定的素材，字体，然后实现日向坂MSG的生成图用处呢？
Regards
喵

**Comment by shoushouminami** [comment]
@yukachan3 你好啊！可以替换素材的，不过再此基础上还需要调节位置和像素之类的，要看你想要的具体效果。有现成的图片我可以看看吗？如果你们是字幕组的话，我可以加你们的qq群。那边聊比较方便。

**Comment by shoushouminami** [comment]
可以发我邮箱 shoushouminami@gmail.com

**Comment by yukachan3** [comment]
谢谢您的回复，我们组暂时解决美工问题，主要我不太会js，所以冒昧问了一下，谢谢您的解答!
Best Regards
Yukachan3

熊猫 <notifications@github.com> 於 2020年12月11日 週五 下午7:45寫道：
